// <auto-generated />
using System;
using BudgetPlanner.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BudgetPlanner.DAL.Migrations
{
    [DbContext(typeof(BudgetDbContext))]
    [Migration("20260112121055_addMonth")]
    partial class addMonth
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BudgetPlanner.DAL.Models.BudgetTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("Month")
                        .HasColumnType("int");

                    b.Property<int>("Recurrence")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("BudgetPlanner.DAL.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Mat",
                            Type = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Hus & drift",
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Transport",
                            Type = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "Fritid",
                            Type = 1
                        },
                        new
                        {
                            Id = 5,
                            Name = "Barn",
                            Type = 1
                        },
                        new
                        {
                            Id = 6,
                            Name = "Streaming-tjänster",
                            Type = 1
                        },
                        new
                        {
                            Id = 7,
                            Name = "SaaS-produkter",
                            Type = 1
                        },
                        new
                        {
                            Id = 8,
                            Name = "Lön",
                            Type = 0
                        },
                        new
                        {
                            Id = 9,
                            Name = "Bidrag",
                            Type = 0
                        },
                        new
                        {
                            Id = 10,
                            Name = "Hobbyverksamhet",
                            Type = 0
                        });
                });

            modelBuilder.Entity("BudgetPlanner.DAL.Models.BudgetTransaction", b =>
                {
                    b.HasOne("BudgetPlanner.DAL.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
